environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
install:
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
build: off
test_script:
  - "%PYTHON%\\python.exe -m unittest discover"
  - "%PYTHON%\\python.exe doctests.py"
  - "%PYTHON%\\python.exe setup.py install"
