#!/usr/bin/env bash

set -e

python -m doctest docs/tutorials/getting_started/*rst
python -m doctest docs/tutorials/further_topics/*rst
python -m doctest docs/reference/*rst
python -m doctest docs/tutorials/contributing/strategy/*rst
python -m doctest docs/tutorials/advanced/strategy_transformers.rst
