name: py35
dependencies:
- python=3.5.1=0
- numpy>=1.9.2
- matplotlib>=1.4.2
- pip:
   - pyparsing==2.1.1 # Due to https://github.com/Axelrod-Python/Axelrod/issues/584
   - hypothesis>=3.2
   - tqdm==3.4.0
   - prompt-toolkit>=1.0.7
