[tox]
# Enable isolated build to ensure compatibility
isolated_build = True
envlist = py311, py312

[gh-actions]
# Map GitHub Actions Python versions to tox environments
python =
    3.11: py311
    3.12: py312

[flake8]
# Ignore specific rules for certain files
per-file-ignores =
    setup.py: F821  # Ignore undefined names in setup.py
    docs/_build/*: ALL  # Ignore all issues in built documentation
    docs/conf.py: E402  # Allow imports not at the top of the file
    **/__init__.py: F401 F403  # Ignore unused imports and wildcard imports in __init__.py
# Global ignores for flake8
ignore =
    E203  # Whitespace before ':'
    E501  # Line length > 80
    W291  # Trailing whitespace
    W503  # Line break before binary operator

[testenv]
deps =
    hypothesis
    pytest-cov
    pytest-randomly
    pytest-sugar
    pytest-xdist  # Added for parallelizing tests
    isort
    black
    numpy==1.26.4
commands =
    # Run tests in parallel using all available CPU cores
    python -m pytest -n auto --cov-report term-missing --cov=axelrod --cov-fail-under=100 . --doctest-glob="*.md" --doctest-glob="*.rst"

    # Check code formatting with Black (no changes are made)
    python -m black -l 80 . --check

    # Verify import sorting with isort
    python -m isort --check-only axelrod/.

    # Run the strategy indexer script
    python run_strategy_indexer.py

