mypy --ignore-missing-imports --follow-imports skip axelrod/actions.py
mypy --ignore-missing-imports --follow-imports skip axelrod/deterministic_cache.py
mypy --ignore-missing-imports --follow-imports skip axelrod/ecosystem.py
mypy --ignore-missing-imports --follow-imports skip axelrod/game.py
mypy --ignore-missing-imports --follow-imports skip axelrod/load_data_.py
mypy --ignore-missing-imports --follow-imports skip axelrod/mock_player.py
mypy --ignore-missing-imports --follow-imports skip axelrod/moran.py
mypy --ignore-missing-imports --follow-imports skip axelrod/plot.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/adaptive.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/alternator.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/appeaser.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/averagecopier.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/calculator.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/forgiver.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/better_and_better.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/darwin.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/cycler.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/cooperator.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/axelrod_second.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/backstabber.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/defector.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/gradualkiller.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/grudger.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/grumpy.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/handshake.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/inverse.py
mypy --ignore-missing-imports --follow-imports skip axelrod/strategies/mathematicalconstants.py
